### ISSUE TITLE
Invalid Resource Id error while the transaction was actually completed successfully

### ISSUE THREAD

**Issue by xiaoleih41** [paypal/PayPal-REST-API-issues#151]
*Migrated issue from https://github.com/paypal/PayPal-PHP-SDK/issues/937*

> For Internal Tracking PPPLMER-39145

Transaction returns with Invalid Resource ID error while Transaction has actually taken place, funds are pulled for authorization or sale.

**Comment by brandonkruse** [comment]
Any work around we can do for this in the meantime?

Does the webhook for authorization still work?

We have 2,000 clients currently affected and trying to figure out a good workaround besides harvesting the 400s and sending emails saying the payment may not have gone through.

**Comment by alexstanbury** [comment]
My issue #152 may be linked to this

**Comment by xelhark** [comment]
@brandonkruse just copypasting my workaround here, hope it helps

I had this problem too.

Just to shed some light on the problem, I noticed that when this happens, there's also a few secondary effects:

Even after the transaction is purchased, the payment returned from the API will always remain in a "created" state, and will contain no sale or transaction data (making it impossible to tie the payment to its sale / transaction)

The Sale object generated by paypal will also be orphan. Meaning that the field "parent_payment_id" will not even appear on the json of the sale object associated with the transaction id (this again, makes it pretty hard to find a way to tie the transaction object with the payment).

I noticed that it looks like when this happens, sometimes, a second execute call (which will happen a lot since users gets an error message) will even result in duplicated transactions. The only way to stop this is to make sure the setting "Block accidental payments" is set to block payments with duplicated invoice IDs (my selling tools > block payments).

As a workaround, I managed to store the payment data in my db (along with other data) and inject my internal payment object id in the "custom" data of the transaction when creating the payment.

This will allow me to always be able to retrieve the data associated with the payment...

..Except this also seem to be happening during recurring payments as well, and there's no custom data there..

What I'm doing in this case is storing my payment id in the first characters of the description, but this is a very ugly (and hackish) solution.. The users will also be able to see that id and it's not the best user experience, since that field has even a 128 character limit..

**Comment by brandonkruse** [comment]
@xiaoleih41  any update here? It's been over a week. This is the worst case scenario - withdrawing funds from the payer's account without a way to track it.

**Comment by xiaoleih41** [comment]
The cause of the issue turned out to be complicated. quite a few scenarios have since been fixed but not for all cases. PayPal is still working on the fix at this time.

**Comment by iamjarret** [comment]
This is crazy.  How long does it take to fix this?  Paypal's restSDK is simply not attaching payer and payment ids to outgoing get requests.  It's really unacceptable that this service is failing in such an egregious way.

**Comment by xiaoleih41** [comment]
It should have been fixed. Close this issue as it is reported that has been fixed.

**Comment by winer632** [comment]
This problem is not solved yet. I met this problem just now in SDK/Library version: 1.12.0. 
I opened an issue in https://github.com/paypal/PayPal-PHP-SDK/issues/980

Paypal is so unreliable, it really disappointed me.

**Comment by xiaoleih41** [comment]
We will address your specific issue on the new thread.

**Comment by kgrosvenor** [comment]
Getting this same issue, any ideas? Its all fine creating subscription billing plans? What is missing??

**Comment by cokeless** [comment]
great payments api

**Comment by tobiascapin** [comment]
Same issue here in sandbox, retrying the same payment ID after a few it starts working.

**Comment by wire67** [comment]
Same here. Can provide debug_id in PM.
