### ISSUE TITLE
INTERNAL_SERVICE_ERROR

### ISSUE THREAD

**Issue by VSilantyev** [paypal/PayPal-REST-API-issues#192]
* Environment: Production
* `PayPal-Debug-ID` values: b054c59b2890c
* Language, language version, and OS:  PHP7 on Ubuntu 16.10

### Issue description

We are trying to bill credit cards saved in vault and for some cards we are receiving errors like:
{"name":"INTERNAL_SERVICE_ERROR","message":"An internal service error occurred.","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"b054c59b2890c"}
Most of the saved cards are billed fine, the error is returned only for some saved cards.

Could you lookup by debug ids, what does INTERNAL_SERVICE_ERROR means?

**Comment by xiaoleih41** [comment]
That could have been caused the expiration year of the card has been expired. Please check into that.

**Comment by pp-randy** [comment]
Vaulted cards are not validated, if you have not had any transactions for these cards it could be invalid input.  However, I am not able to determine a root cause from the logging.  Since this is impacting your production integration, please reach out to PayPal Technical Support for further investigation at https://www.paypal-techsupport.com/app/ask.

**Comment by pp-randy** [comment]
Sorry for not answering your question otherwise. An `INTERNAL_SERVICE_ERROR` is a PayPal service issue and should be investigated, so thank you for reaching out.

**Comment by VSilantyev** [comment]
Thank you, BTW - I've checked the vaulted card, it has valid expiration date
