### ISSUE TITLE
Subscription Activate?

### ISSUE THREAD

**Issue by updatesvc** [paypal/PayPal-REST-API-issues#312]
### General information

* Environment: Sandbox

### Issue description
Do I need send an [activate request](https://developer.paypal.com/docs/subscriptions/full-integration/subscription-management/#activate-subscription) for every  new subscription created?
Workflow Create Sub ->user approves->send activate request to paypal-> get sale.oayment complete
Then do server side logic for processing new subscription

Do i need to do the activate part, its seem counter intuitive since the user already approved it.

**Comment by YassienW** [comment]
This is probably sorted out by now, but since paypal support is horrendous i'll answer it for others.

 By default once the customer approves the subscription it is automatically activated and the "Subscription Activated" webhook is called, you can change this by altering the `user_action` variable in the [application context](https://developer.paypal.com/docs/api/subscriptions/v1/#definition-application_context) when creating the subscription.

**Comment by updatesvc** [comment]
thanks
