### ISSUE TITLE
Wrong total label

### ISSUE THREAD

**Issue by jaypatel512** [paypal/PayPal-REST-API-issues#52]
*Migrated issue from https://github.com/paypal/PayPal-PHP-SDK/issues/803*

> For internal bookkeeping: PPPLMER-28975

The PayPal website is missing my $total and just shows "Subtotal" … but with the correct total amount.

The part from the $transaction object:
```
[amount] => PayPal\Api\Amount Object
(
	[_propMap:PayPal\Common\PayPalModel:private] => Array
		(
			[currency] => EUR
			[total] => 490.80
			[details] => PayPal\Api\Details Object
				(
					[_propMap:PayPal\Common\PayPalModel:private] => Array
						(
							[shipping] => 45
							[subtotal] => 445.80
						)

				)

		)

)
```

![paypal_checkout_-_log_in](https://cloud.githubusercontent.com/assets/1328092/23890369/e0b4615e-0891-11e7-9257-011579aaccc2.png)

**Comment by bluk** [comment]
The reason why `Subtotal` is shown is because the amount may be adjusted by the merchant at this point in the checkout process.

In order to change `Subtotal` to `Total` and to give a final amount (which cannot be adjusted by the merchant after the checkout process), you can add the `&useraction=commit` query parameter to the payment approval URL like:

`https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-SAMPLEID&useraction=commit`

Or you can create a [Payment Experience profile](https://developer.paypal.com/docs/api/payment-experience/), set the [`flow_config.user_action` value to be `commit`](https://developer.paypal.com/docs/api/payment-experience/#definition-flow_config). Then, when you create a payment, [add the `experience_profile_id` to the request](https://developer.paypal.com/docs/api/payments/#payment_create_request).

See the documentation for the `flow_config.user_action` for more details.
