### ISSUE TITLE
Multiple refunds via REST API

### ISSUE THREAD

**Issue by timmixell** [paypal/PayPal-REST-API-issues#60]
> Known workarounds or alternative products: N/A

> For internal bookkeeping: PPPLPAYPT-20210

### General information

* Environment: Sandbox
* `PayPal-Debug-ID` values: dbc3bea922824, 9346aa7b93f9d, 59d771c377056

### Issue description

When using the refund endpoint: https://developer.paypal.com/docs/api/payments/#refund - a partial refund is successful, but subsequent attempts to perform another partial refund yield an `UNKNOWN_ERROR`. I haven't been able to find anything in the documentation that indicates this isn't permissible.

**Comment by pp-randy** [comment]
The issue is related to using the same [`invoice_number`](https://developer.paypal.com/docs/api/payments/#sale_refund_request) parameter with the refund requests.  

Currently, you should be able to create multiple partial refunds if you change the invoice_number, or don't included the parameter in the refund. 

The bug is that the REST API did not expose the error to you.  I will be follow up further with more details to track the issue.

**Comment by timmixell** [comment]
that solved my problem. thanks, @pp-randy . i'll leave the issue open until directed otherwise. i'm more than happy to test an invalid call to confirm a *known* error response.

**Comment by pp-randy** [comment]
Yes, lets leave this open if you are good with it. I edited your initial comment with some internal tracking information.

**Comment by pp-randy** [comment]
For duplicate invoice number the follow error should now be returned.
```
{"name":"DUPLICATE_TRANSACTION","message":"Requested invoice number was already used.","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#DUPLICATE_TRANSACTION","debug_id":"XXXXXXXXXX"}
```
